apiVersion: v1
kind: ConfigMap
metadata:
  name: persistencecore
data:
  chain.id: persistencecore

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firehose-node-config
data:
  sync_node.resolution_method: DYNAMIC
  sync_node.host: 'persistencecore-genesis.dev-core.svc.cluster.local'
  sync_node.exposer_port: '8081'
  sync_node.port_p2p: '26656'
  sync_node.genesis_json_fetch_url: ''
  snapshot_restore_url: ''
  seeds: ''