namespace: testnet

resources:
  # - ingress.yaml
  - ../../graph-node
  - configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/genesis_node_data_resolution_method
      value: STATIC
    - op: replace
      path: /spec/template/metadata/annotations/genesis_host
      value: "3.34.2.126"
    - op: replace
      path: /spec/template/metadata/annotations/genesis_exposer_port
      value: ''
    - op: replace
      path: /spec/template/metadata/annotations/genesis_json_fetch_url
      value: "https://raw.githubusercontent.com/persistenceOne/networks/master/test-core-1/final_genesis.json"
    - op: replace
      path: /spec/template/metadata/annotations/state_restore_snapshot_url
      value: "https://tendermint-snapshots.s3.ap-southeast-1.amazonaws.com/persistence/testnet/test.tar.gz"
  target:
    kind: StatefulSet
    name: persistencecore-firehose-node
- patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/firehose_host
      value: 'persistencecore-firehose-node.testnet'
    - op: replace
      path: /spec/template/metadata/annotations/firehose_port
      value: '9030'
    - op: replace
      path: /spec/template/metadata/annotations/ipfs_host
      value: 'ipfs.testnet'
    - op: replace
      path: /spec/template/metadata/annotations/ipfs_port
      value: '5001'
  target:
    kind: StatefulSet
    name: persistencecore-graph-node