chains:
  - name: core-1
    type: persistencecore
    numValidators: 2
    upgrade:
      enabled: false
      type: build
      genesis: v6.1.0
      upgrades:
        - name: v7-rc1
          version: manasi/v7-rc1
    ports:
      rpc: 26657
      rest: 1317
      p2p: 26656

explorer:
  enabled: true
