chains:
  - name: core-1
    type: persistencecore
    numValidators: 4
    upgrade:
      enabled: true
      type: build
      genesis: v6.0.0-rc4
      upgrades:
        - name: v6-rc5
          version: anmol/v6-rc5
    ports:
      rpc: 26657
      rest: 1317
      p2p: 26656
      exposer: 9080

explorer:
  enabled: true
